# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 794dba26c3bb01ac77ea4e0d72ed0bb015ae07a6b21564956b076438c77beca36b3fff9d5f97d3eddfb12fbdc5a777cf0efd69ca43edf1bf73a7897c334580fb

test:
  secret_key_base: 898b67a7cdd40d80946a3a9c6b5c60540842f3fb7aa886d4f14b3b3992a4f16c792725379907c59bd21b721c19979ebf7c17ab478ebf06cfda8c8ea1beb51a61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
